// React/01react-core/src/components/TreeItem.js
import React, { useState } from 'react'
import classnames from "classnames";

export default function TreeItem(props) {
    let [expanded, setExpanded] = useState(false)
    const handleExpanded = () => {
        setExpanded(!expanded)
    }

    const { title, children } = props.data
    const hasChildren = children && Array.isArray(children) && children.length > 0

    return (
        <div className="tree-item" >
            <div className="nodeInner" onClick={() => handleExpanded()}>
                {
                    hasChildren &&
                    <i className={classnames('tri', expanded ? "tri-open" : "tri-close")}></i>
                }
                <span>{title}</span>
            </div>
            {
                hasChildren && expanded && (
                    <div className="children">
                        {
                            children.map(child => <TreeItem key={child.key} data={child} />)
                        }
                    </div>
                )
            }
        </div>
    )
}

// Vue/01component/src/components/Tree/TreeItem.vue
<template>
  <li class="tree-item-comp">
    <div class="tree-item-hd" @click="toggle">
      {{model.title}}
      <span class="toggle-icon" v-if="isFolder">[{{open? '-': '+'}}]</span>
    </div>
    <!-- 递归子Item -->
    <ul v-if="isFolder" v-show="open">
      <tree-item v-for="model in model.children" :model="model" :key="model.title"></tree-item>
    </ul>
  </li>
</template>

<script>
export default {
  name: "TreeItem",
  props: {
    model: {
      type: Object
    }
  },
  data() {
    return {
      open: false
    };
  },
  computed: {
    isFolder() {
      return this.model.children && this.model.children.length;
    }
  },
  methods: {
    toggle() {
      if (this.isFolder) {
        this.open = !this.open;
      }
    }
  }
};
</script>

<style lang="scss" scoped>
.tree-item-comp {
  li {
    text-indent: 1em;
    li {
      text-indent: 2em;
      li {
        text-indent: 3em;
      }
    }
  }
}
</style>
